Add Support for CF.ADDNX
predis/predis pull request #1048
Opened 2023-01-29 16:18 UTC by shacharPash

2023-01-30 07:16 UTC, vladvildanov requested changes

2023-01-30 07:16 UTC, vladvildanov commented on tests/Predis/Command/Redis/CuckooFilter/CFADDNX_Test.php
> +        $redis->cfadd('cfadd_foo', 'foo');
Should be `cfaddnx` instead

2023-01-31 10:34 UTC, shacharPash commented
ref #895

2023-01-31 10:35 UTC, vladvildanov requested changes

2023-01-31 10:35 UTC, vladvildanov commented on tests/Predis/Command/Redis/CuckooFilter/CFADDNX_Test.php
> +        $redis->cfadd('cfaddnx_foo', 'foo');
The command itself, still incorrect, should be `$redis->cfaddnx(...)`

2023-01-31 11:25 UTC, merged