Relay support
predis/predis pull request #1084
Opened 2023-01-31 16:47 UTC by tillkruss

This is a work in progress.

## TODOs

- [x] Deprecate phpiredis + webdis now
- [x] Pass most Redis Stack tests
- [x] Replace `phpiredis` instructions with Relay instructions
- [x] Pass most tests (except `relay-incompatible` group)
- [x] Remove all `relay-*` groups except `relay-incompatible`
- [ ] Add `examples/relay_events.php` 
- [ ] Finish [Wiki page](https://github.com/predis/predis/wiki)
- [ ] Make `onInvalidated()` and other methods easier to access

## Followup
- Support `compression` and `serializer` options and handle `Predis\Command\RawCommand()` calls 
- Review `relay-fixme` test group

## Tests

```bash
./vendor/bin/phpunit -c phpunit.relay.xml --exclude-group slow,relay-incompatible
```

2023-02-08 15:49 UTC, szepeviktor commented
@tillkruss Please consider not naming that branch like a tag.
It could be `3.x` or something ...

2023-02-08 16:38 UTC, szepeviktor commented
> how can we rename

Maybe keep both old and new until you merge all 5 other PR-s.

2023-02-21 02:00 UTC, szepeviktor commented
This seems unsporrted

> ✗ relay Could not install relay on PHP 7.2.34

2023-02-22 19:55 UTC, szepeviktor commented
> 2780 Segmentation fault      (core dumped)

It this message from Relay?

2023-02-22 21:19 UTC, tillkruss commented
> > 2780 Segmentation fault      (core dumped)
> 
> It this message from Relay?

No, that’s PHP crashing. This is a WIP, no need to review it.

2023-03-03 09:29 UTC, vladvildanov requested changes

2023-03-03 14:15 UTC, tillkruss commented on src/Command/Redis/COMMAND.php
> +        // Relay (RESP3) uses maps and it might be good
Relay is RESP3 only, but Predis itself can remain RESP2 for now 👍

2023-03-03 14:17 UTC, tillkruss commented on .github/workflows/tests.yml
> +      - name: Run tests using Relay
The first step runs all Predis tests, the 2nd step runs to gather code coverage. 

The 3rd step I added runs all unit tests using Relay to ensure it acts just like Predis expects.

2023-03-03 16:49 UTC, tillkruss commented on src/Transaction/MultiExec.php
> +            if ($execResponse === null || $execResponse === false) {
I rather leave it strict for now, `empty()` has too many falsey cases.

2023-03-06 08:25 UTC, vladvildanov commented on src/Command/Redis/COMMAND.php
> +        // Relay (RESP3) uses maps and it might be good
@chayim Adding RESP3 support is also a near future change that should be done. It looks like to cover RESP3 needs it's more changes requires, right now we have a lot of discussion around it.

2023-03-06 16:31 UTC, tillkruss commented on src/Command/Redis/COMMAND.php
> +        // Relay (RESP3) uses maps and it might be good
Is that something you want to squeeze into v3, or into a future release?

2023-04-14 20:41 UTC, closed without merging