Adding key processor prefix for the newly added FCALL command
predis/predis pull request #1189
Opened 2023-03-05 16:37 UTC by mehrud

Key prefix processor for functions [Redis 7.0] is missing. The new-brand function feature has been added to this package, but unfortunately, the prefix processor has not been implemented.

2023-03-05 16:53 UTC, tillkruss approved these changes

2023-03-08 08:42 UTC, mehrud commented
May I have any update on this? We need this functionality as soon as possible

2023-03-08 17:53 UTC, tillkruss commented
@mehrud: Can you add a test case to cover the new functionality?

2023-03-14 14:49 UTC, vladvildanov approved these changes

2023-03-14 18:14 UTC, tillkruss requested changes
Please add a test.

2023-03-17 22:04 UTC, mehrud commented
No need, we decided to migrate to phpredis

2023-03-28 13:33 UTC, closed without merging