Added support for XREADGROUP command
predis/predis pull request #1327
Opened 2023-06-20 13:03 UTC by vladvildanov

Closes #1326

2023-06-20 13:44 UTC, tillkruss approved these changes

2023-07-02 11:16 UTC, chayim requested changes
Let's get more tests in place. XREADGROUP accepts key [key ...] id [id...] , so I think we're missing at least one test case (multiple if you think of ID as a list).

2023-07-04 14:03 UTC, vladvildanov commented
@chayim Done!

2023-07-09 12:01 UTC, chayim approved these changes

2023-07-26 13:50 UTC, merged