Fix prefix error if prefix equals a php command
predis/predis pull request #1339
Opened 2023-07-20 12:13 UTC by mmodler

Fix php error if prefix equals a php command like "chr" for example.

Replaced is_callable with instanceof Closure, which should preserve the desired behavior.

2023-07-20 12:16 UTC, mmodler commented
I'm not sure if its security related and justifies a hotfix release?

2023-07-20 17:06 UTC, tillkruss commented
This would remove some functionality, please explain what this fixes with a test case. I don't understand what this resolves.

2023-09-08 06:30 UTC, mmodler commented
Set the prefix to a php command like `chr`

`$client = new Predis\Client($parameters, ['prefix' => 'chr']);`

Then is_callable() is true and the command is executed with  call_user_func().

2023-09-08 16:17 UTC, tillkruss requested changes
Tests are failing.

2023-09-13 16:49 UTC, closed without merging

2023-09-14 06:13 UTC, mmodler commented
Did you get the point?

2023-09-14 16:43 UTC, tillkruss commented
No, we need unit tests to explain this change, since it **narrowing** the accepted type from `callable` to `Closure`.

2023-09-15 13:05 UTC, mmodler commented
Hm, do you understand the problem and someone needs to fix the tests? Or do you ask me WHY this should be narrowed?

2023-09-15 16:49 UTC, tillkruss commented
Yes, I understand the issue, but we don't merge PRs without tests.