Added support for PrefixableCommandInterface (#1262)
predis/predis pull request #1343
Opened 2023-07-25 07:52 UTC by chayim

2023-07-26 08:15 UTC, vladvildanov approved these changes

2023-07-26 16:06 UTC, tillkruss requested changes

2023-07-26 16:06 UTC, tillkruss commented on README.md
> +These same parameters, can be extended to add support for the RESP 3 protocol:
Can we explain the benefits of using RESP3 as well to avoid people asking?

2023-08-03 07:39 UTC, vladvildanov approved these changes

2023-08-06 09:28 UTC, closed without merging