Spellcheck as part of CI
predis/predis pull request #1353
Opened 2023-08-06 09:29 UTC by chayim

As part of extending CI and providing a better experience working with the repository and codebase itself, I'm starting by adding some scaffolding, spelling CI.

2023-10-22 06:31 UTC, chayim commented
Reminder @vladvildanov . It's in elsewhere, can we finish merging this>?

2023-10-23 07:07 UTC, vladvildanov approved these changes

2023-10-23 07:08 UTC, vladvildanov commented
@chayim I'll fix broken Ci and we're good to go

2023-10-23 07:35 UTC, vladvildanov approved these changes

2023-10-23 07:35 UTC, vladvildanov commented
@chayim @tillkruss Good to go

2023-10-23 18:47 UTC, tillkruss requested changes

2023-10-23 18:47 UTC, tillkruss commented on .github/workflows/linters.yml
> -        run: $(python -m site --user-base)/bin/codespell
Can we keep the spellcheck in the `linters.yml`, or is there a good reason why not?

2023-10-23 18:47 UTC, tillkruss commented on src/Connection/Replication/SentinelReplication.php
> +        try {
Please remove code changes from this PR that are not related to spelling.

2024-01-02 18:02 UTC, closed without merging