ZPOPMIN & ZPOPMAX with "prefix first" option added to the KeyPrefixProcessor
predis/predis pull request #1432
Opened 2024-02-09 22:10 UTC by sngrl

2024-02-10 16:25 UTC, tillkruss approved these changes

2024-02-12 07:18 UTC, vladvildanov commented
@sngrl Would you mind to add a test coverage? Literally, it's just about extending already existing data provider in unit tests

2024-02-12 10:50 UTC, sngrl2 commented
@vladvildanov tests already are presented, my PR just makes this commands to use prefixes
```php
\Predis\Command\Redis\ZPOPMIN_Test
\Predis\Command\Redis\ZPOPMAX_Test
```

2024-02-13 07:20 UTC, vladvildanov approved these changes

2024-02-13 07:21 UTC, vladvildanov commented
@sngrl2 Ah, my bad! Approved

But you also need to run `composer style:fix` command to fix codestyle issues

2025-02-13 17:13 UTC, tillkruss requested changes

2025-02-13 17:13 UTC, tillkruss commented on src/Command/Processor/KeyPrefixProcessor.php
> +            'ZPOPMAX' => $prefixFirst,
Needs tests.

2025-04-15 11:09 UTC, vladvildanov commented
@tillkruss Ready to merge

2025-04-15 15:40 UTC, tillkruss commented
@vladvildanov Did you undo the commit? 🫠

2025-04-15 18:56 UTC, tillkruss approved these changes

2025-04-15 20:25 UTC, merged