Added support for transactions in OSS Cluster
predis/predis pull request #1484
Opened 2024-10-21 15:02 UTC by vladvildanov

This PR adds a support for transaction execution against distributed hash-slot environment. 

The core idea is to allow a transaction execution against same hash slot to keep data atomicity. In Cluster environments the commands are queued until it's possible to calculate hash slot and ensure that commands are operated against a same slot

2024-10-22 07:53 UTC, vladvildanov commented
@tillkruss Why does it marked as breaking change?

2024-10-22 12:22 UTC, vladvildanov commented
@tillkruss Blocked by #1485

2024-10-22 15:56 UTC, dmaier-redislabs submitted a review, later dismissed
Looks good from my point of view. @tillkruss It seems that an approval by you is needed. Could you please review and approve?

2024-10-22 16:18 UTC, tillkruss commented
> Why does it marked as breaking change?

@vladvildanov: Some interfaces changed and new return types for methods. That would break if someone has their own implementation.

2024-10-23 08:12 UTC, vladvildanov commented
@tillkruss Well, the interfaces was extended with new methods and there's no changes to existing one. The return types wasn't changed they were defined in the places where the definition is missing, also changes to functions and constructor signatures is backward compatible. So I disagree that this can be consider as breaking.

Let me know if you meant something specific in this PR.

2024-10-29 18:13 UTC, tillkruss commented
> Well, the interfaces was extended with new methods and there's no changes to existing one.

Adding a new method to an interface is a breaking change.

If you want to dig up some official SemVer rules on this we can nitpick it, maybe PHP-FIG or a similar group has some?

2024-11-06 13:46 UTC, vladvildanov commented
@tillkruss Hmm, PHP-FIG doesn't elaborate on semantic versioning, so I guess we can jump into official docs from https://semver.org/.
```
Given a version number MAJOR.MINOR.PATCH, increment the:

1. MAJOR version when you make incompatible API changes
2. MINOR version when you add functionality in a backward compatible manner
3. PATCH version when you make backward compatible bug fixes
```

Well, extending the existing interface with a new method can be consider as a `add functionality in a backward compatible manner`, it doesn't break any existing behaviour and doesn't impact the end user. The same could be applied for any function signature that was extended with additional optional arguments, if arguments order was kept.

2024-11-08 17:03 UTC, tillkruss commented
>Well, extending the existing interface with a new method can be consider as add functionality in a backward compatible manner

Not in my books. IMO it's a breaking change.

- https://github.com/phpredis/phpredis/issues/2562
- https://github.com/phpredis/phpredis/issues/2564

```php
<?php

interface StrategyInterface {
  public function getSlot(string $command);
  public function checkSameSlotForKeys(array $keys): bool;
}

class StrategyTest implements StrategyInterface {
  public function getSlot(string $command) {
    // Your implementation here
  }
}

$test = new StrategyTest();
```

2024-11-21 15:01 UTC, vladvildanov commented
@tillkruss Okay, it's up to you. Appreciate your review in any case

2024-12-05 17:20 UTC, tillkruss requested changes
Looks good, just need to change the branch to v3.x

2025-01-13 09:14 UTC, closed without merging