Add retry logic to support temporary redis cluster failure (\Predis\C…
predis/predis pull request #732
Opened 2021-12-29 15:01 UTC by digital2real

This changes are trying to complete the retry logic in order to increase the tolerance to a temporary unavailability of a redis cluster.

(Sorry for previous PR #731 on main)

2022-01-06 17:38 UTC, tillkruss commented
No worries.

@nrk Any input on this?

2022-02-18 14:39 UTC, digital2real commented
Hi,
@tillkruss , @nrk do you have any comment/update on this?

2022-02-18 14:45 UTC, tillkruss requested changes

2022-02-18 14:45 UTC, tillkruss commented on src/Connection/Aggregate/RedisCluster.php
> +		        sleep(2^$retries);
Indentation seems off.

2022-02-18 14:45 UTC, tillkruss commented on src/Connection/Aggregate/RedisCluster.php
> +        $retries= 0 ;
Needs formatting.

2022-02-18 14:45 UTC, tillkruss commented on src/Connection/Aggregate/RedisCluster.php
> +                if (is_a($response, '\\Predis\\Response\\Error')){
Use `instanceof` please.

2022-02-18 14:45 UTC, tillkruss commented on src/Connection/Aggregate/RedisCluster.php
> +            } catch (ConnectionException|ServerException $exception) {
I don't think this syntax is compatible with olde PHP versions.

2022-05-26 18:38 UTC, tillkruss commented
Feel free to re-submit to the 2.0 `main` branch.

2022-05-26 18:38 UTC, closed without merging